-- 033 Fix movement_reports schema mismatch
DROP TABLE IF EXISTS movement_reports CASCADE;

CREATE TABLE movement_reports (
    id                          BIGSERIAL PRIMARY KEY,
    imei                        TEXT NOT NULL,
    vehicle_id                  INT REFERENCES vehicles(id) ON DELETE CASCADE,
    report_date                 DATE NOT NULL,
    average_speed               FLOAT,
    total_distance              FLOAT,
    start_point                 JSONB,
    end_point                   JSONB,
    start_time                  TIMESTAMPTZ,
    end_time                    TIMESTAMPTZ,
    alert                       INT DEFAULT 0,
    total_active_duration       TEXT,
    total_idle_duration         TEXT,
    total_stoppage_duration     TEXT,
    in_parking_duration         TEXT,
    actual_ignition_on_duration TEXT,
    total_ignition_on_duration  TEXT,
    total_running_duration      TEXT,
    total_running_time          TEXT,
    day_running_time            TEXT,
    night_running_time          TEXT,
    fuel_in_ltr                 FLOAT DEFAULT 0,
    fuel_consumption            FLOAT DEFAULT 0,
    speed_limit                 FLOAT DEFAULT 0,
    max_speed                   FLOAT DEFAULT 0,
    min_speed                   FLOAT DEFAULT 0,
    overspeed_distance          FLOAT DEFAULT 0,
    overspeed_count             TEXT DEFAULT '0',
    overspeed_time              TEXT DEFAULT '0',
    zone                        VARCHAR(255),
    ward                        VARCHAR(255),
    stoppages_count             INTEGER DEFAULT 0,
    created_at                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(imei, report_date)
);
